/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublisherAuthLayoutRouteImport } from './routes/_publisherAuthLayout'
import { Route as OverseerAuthLayoutRouteImport } from './routes/_overseerAuthLayout'
import { Route as AssistantAuthLayoutRouteImport } from './routes/_assistantAuthLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublisherAuthLayoutVacantShiftsRouteImport } from './routes/_publisherAuthLayout/vacantShifts'
import { Route as PublisherAuthLayoutMyShiftsRouteImport } from './routes/_publisherAuthLayout/myShifts'
import { Route as PublisherAuthLayoutMyScheduleRouteImport } from './routes/_publisherAuthLayout/mySchedule'

const OverseerAuthLayoutSitesLazyRouteImport = createFileRoute(
  '/_overseerAuthLayout/sites',
)()
const OverseerAuthLayoutSettingLazyRouteImport = createFileRoute(
  '/_overseerAuthLayout/setting',
)()
const OverseerAuthLayoutOverviewLazyRouteImport = createFileRoute(
  '/_overseerAuthLayout/overview',
)()
const AssistantAuthLayoutUsersLazyRouteImport = createFileRoute(
  '/_assistantAuthLayout/users',
)()
const AssistantAuthLayoutShiftsLazyRouteImport = createFileRoute(
  '/_assistantAuthLayout/shifts',
)()

const PublisherAuthLayoutRoute = PublisherAuthLayoutRouteImport.update({
  id: '/_publisherAuthLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const OverseerAuthLayoutRoute = OverseerAuthLayoutRouteImport.update({
  id: '/_overseerAuthLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantAuthLayoutRoute = AssistantAuthLayoutRouteImport.update({
  id: '/_assistantAuthLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverseerAuthLayoutSitesLazyRoute =
  OverseerAuthLayoutSitesLazyRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => OverseerAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_overseerAuthLayout/sites.lazy').then((d) => d.Route),
  )
const OverseerAuthLayoutSettingLazyRoute =
  OverseerAuthLayoutSettingLazyRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => OverseerAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_overseerAuthLayout/setting.lazy').then((d) => d.Route),
  )
const OverseerAuthLayoutOverviewLazyRoute =
  OverseerAuthLayoutOverviewLazyRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => OverseerAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_overseerAuthLayout/overview.lazy').then((d) => d.Route),
  )
const AssistantAuthLayoutUsersLazyRoute =
  AssistantAuthLayoutUsersLazyRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AssistantAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_assistantAuthLayout/users.lazy').then((d) => d.Route),
  )
const AssistantAuthLayoutShiftsLazyRoute =
  AssistantAuthLayoutShiftsLazyRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => AssistantAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_assistantAuthLayout/shifts.lazy').then((d) => d.Route),
  )
const PublisherAuthLayoutVacantShiftsRoute =
  PublisherAuthLayoutVacantShiftsRouteImport.update({
    id: '/vacantShifts',
    path: '/vacantShifts',
    getParentRoute: () => PublisherAuthLayoutRoute,
  } as any)
const PublisherAuthLayoutMyShiftsRoute =
  PublisherAuthLayoutMyShiftsRouteImport.update({
    id: '/myShifts',
    path: '/myShifts',
    getParentRoute: () => PublisherAuthLayoutRoute,
  } as any)
const PublisherAuthLayoutMyScheduleRoute =
  PublisherAuthLayoutMyScheduleRouteImport.update({
    id: '/mySchedule',
    path: '/mySchedule',
    getParentRoute: () => PublisherAuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mySchedule': typeof PublisherAuthLayoutMyScheduleRoute
  '/myShifts': typeof PublisherAuthLayoutMyShiftsRoute
  '/vacantShifts': typeof PublisherAuthLayoutVacantShiftsRoute
  '/shifts': typeof AssistantAuthLayoutShiftsLazyRoute
  '/users': typeof AssistantAuthLayoutUsersLazyRoute
  '/overview': typeof OverseerAuthLayoutOverviewLazyRoute
  '/setting': typeof OverseerAuthLayoutSettingLazyRoute
  '/sites': typeof OverseerAuthLayoutSitesLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mySchedule': typeof PublisherAuthLayoutMyScheduleRoute
  '/myShifts': typeof PublisherAuthLayoutMyShiftsRoute
  '/vacantShifts': typeof PublisherAuthLayoutVacantShiftsRoute
  '/shifts': typeof AssistantAuthLayoutShiftsLazyRoute
  '/users': typeof AssistantAuthLayoutUsersLazyRoute
  '/overview': typeof OverseerAuthLayoutOverviewLazyRoute
  '/setting': typeof OverseerAuthLayoutSettingLazyRoute
  '/sites': typeof OverseerAuthLayoutSitesLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_assistantAuthLayout': typeof AssistantAuthLayoutRouteWithChildren
  '/_overseerAuthLayout': typeof OverseerAuthLayoutRouteWithChildren
  '/_publisherAuthLayout': typeof PublisherAuthLayoutRouteWithChildren
  '/_publisherAuthLayout/mySchedule': typeof PublisherAuthLayoutMyScheduleRoute
  '/_publisherAuthLayout/myShifts': typeof PublisherAuthLayoutMyShiftsRoute
  '/_publisherAuthLayout/vacantShifts': typeof PublisherAuthLayoutVacantShiftsRoute
  '/_assistantAuthLayout/shifts': typeof AssistantAuthLayoutShiftsLazyRoute
  '/_assistantAuthLayout/users': typeof AssistantAuthLayoutUsersLazyRoute
  '/_overseerAuthLayout/overview': typeof OverseerAuthLayoutOverviewLazyRoute
  '/_overseerAuthLayout/setting': typeof OverseerAuthLayoutSettingLazyRoute
  '/_overseerAuthLayout/sites': typeof OverseerAuthLayoutSitesLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mySchedule'
    | '/myShifts'
    | '/vacantShifts'
    | '/shifts'
    | '/users'
    | '/overview'
    | '/setting'
    | '/sites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mySchedule'
    | '/myShifts'
    | '/vacantShifts'
    | '/shifts'
    | '/users'
    | '/overview'
    | '/setting'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/_assistantAuthLayout'
    | '/_overseerAuthLayout'
    | '/_publisherAuthLayout'
    | '/_publisherAuthLayout/mySchedule'
    | '/_publisherAuthLayout/myShifts'
    | '/_publisherAuthLayout/vacantShifts'
    | '/_assistantAuthLayout/shifts'
    | '/_assistantAuthLayout/users'
    | '/_overseerAuthLayout/overview'
    | '/_overseerAuthLayout/setting'
    | '/_overseerAuthLayout/sites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantAuthLayoutRoute: typeof AssistantAuthLayoutRouteWithChildren
  OverseerAuthLayoutRoute: typeof OverseerAuthLayoutRouteWithChildren
  PublisherAuthLayoutRoute: typeof PublisherAuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_publisherAuthLayout': {
      id: '/_publisherAuthLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublisherAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_overseerAuthLayout': {
      id: '/_overseerAuthLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OverseerAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_assistantAuthLayout': {
      id: '/_assistantAuthLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AssistantAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_overseerAuthLayout/sites': {
      id: '/_overseerAuthLayout/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof OverseerAuthLayoutSitesLazyRouteImport
      parentRoute: typeof OverseerAuthLayoutRoute
    }
    '/_overseerAuthLayout/setting': {
      id: '/_overseerAuthLayout/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof OverseerAuthLayoutSettingLazyRouteImport
      parentRoute: typeof OverseerAuthLayoutRoute
    }
    '/_overseerAuthLayout/overview': {
      id: '/_overseerAuthLayout/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverseerAuthLayoutOverviewLazyRouteImport
      parentRoute: typeof OverseerAuthLayoutRoute
    }
    '/_assistantAuthLayout/users': {
      id: '/_assistantAuthLayout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AssistantAuthLayoutUsersLazyRouteImport
      parentRoute: typeof AssistantAuthLayoutRoute
    }
    '/_assistantAuthLayout/shifts': {
      id: '/_assistantAuthLayout/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AssistantAuthLayoutShiftsLazyRouteImport
      parentRoute: typeof AssistantAuthLayoutRoute
    }
    '/_publisherAuthLayout/vacantShifts': {
      id: '/_publisherAuthLayout/vacantShifts'
      path: '/vacantShifts'
      fullPath: '/vacantShifts'
      preLoaderRoute: typeof PublisherAuthLayoutVacantShiftsRouteImport
      parentRoute: typeof PublisherAuthLayoutRoute
    }
    '/_publisherAuthLayout/myShifts': {
      id: '/_publisherAuthLayout/myShifts'
      path: '/myShifts'
      fullPath: '/myShifts'
      preLoaderRoute: typeof PublisherAuthLayoutMyShiftsRouteImport
      parentRoute: typeof PublisherAuthLayoutRoute
    }
    '/_publisherAuthLayout/mySchedule': {
      id: '/_publisherAuthLayout/mySchedule'
      path: '/mySchedule'
      fullPath: '/mySchedule'
      preLoaderRoute: typeof PublisherAuthLayoutMyScheduleRouteImport
      parentRoute: typeof PublisherAuthLayoutRoute
    }
  }
}

interface AssistantAuthLayoutRouteChildren {
  AssistantAuthLayoutShiftsLazyRoute: typeof AssistantAuthLayoutShiftsLazyRoute
  AssistantAuthLayoutUsersLazyRoute: typeof AssistantAuthLayoutUsersLazyRoute
}

const AssistantAuthLayoutRouteChildren: AssistantAuthLayoutRouteChildren = {
  AssistantAuthLayoutShiftsLazyRoute: AssistantAuthLayoutShiftsLazyRoute,
  AssistantAuthLayoutUsersLazyRoute: AssistantAuthLayoutUsersLazyRoute,
}

const AssistantAuthLayoutRouteWithChildren =
  AssistantAuthLayoutRoute._addFileChildren(AssistantAuthLayoutRouteChildren)

interface OverseerAuthLayoutRouteChildren {
  OverseerAuthLayoutOverviewLazyRoute: typeof OverseerAuthLayoutOverviewLazyRoute
  OverseerAuthLayoutSettingLazyRoute: typeof OverseerAuthLayoutSettingLazyRoute
  OverseerAuthLayoutSitesLazyRoute: typeof OverseerAuthLayoutSitesLazyRoute
}

const OverseerAuthLayoutRouteChildren: OverseerAuthLayoutRouteChildren = {
  OverseerAuthLayoutOverviewLazyRoute: OverseerAuthLayoutOverviewLazyRoute,
  OverseerAuthLayoutSettingLazyRoute: OverseerAuthLayoutSettingLazyRoute,
  OverseerAuthLayoutSitesLazyRoute: OverseerAuthLayoutSitesLazyRoute,
}

const OverseerAuthLayoutRouteWithChildren =
  OverseerAuthLayoutRoute._addFileChildren(OverseerAuthLayoutRouteChildren)

interface PublisherAuthLayoutRouteChildren {
  PublisherAuthLayoutMyScheduleRoute: typeof PublisherAuthLayoutMyScheduleRoute
  PublisherAuthLayoutMyShiftsRoute: typeof PublisherAuthLayoutMyShiftsRoute
  PublisherAuthLayoutVacantShiftsRoute: typeof PublisherAuthLayoutVacantShiftsRoute
}

const PublisherAuthLayoutRouteChildren: PublisherAuthLayoutRouteChildren = {
  PublisherAuthLayoutMyScheduleRoute: PublisherAuthLayoutMyScheduleRoute,
  PublisherAuthLayoutMyShiftsRoute: PublisherAuthLayoutMyShiftsRoute,
  PublisherAuthLayoutVacantShiftsRoute: PublisherAuthLayoutVacantShiftsRoute,
}

const PublisherAuthLayoutRouteWithChildren =
  PublisherAuthLayoutRoute._addFileChildren(PublisherAuthLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantAuthLayoutRoute: AssistantAuthLayoutRouteWithChildren,
  OverseerAuthLayoutRoute: OverseerAuthLayoutRouteWithChildren,
  PublisherAuthLayoutRoute: PublisherAuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
