/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutVacantShiftsRouteImport } from './routes/_authLayout/vacantShifts'
import { Route as AuthLayoutAdminLayoutRouteImport } from './routes/_authLayout/_adminLayout'

const AuthLayoutMyShiftsLazyRouteImport = createFileRoute(
  '/_authLayout/myShifts',
)()
const AuthLayoutMyScheduleLazyRouteImport = createFileRoute(
  '/_authLayout/mySchedule',
)()
const AuthLayoutAdminLayoutUsersLazyRouteImport = createFileRoute(
  '/_authLayout/_adminLayout/users',
)()
const AuthLayoutAdminLayoutSitesLazyRouteImport = createFileRoute(
  '/_authLayout/_adminLayout/sites',
)()
const AuthLayoutAdminLayoutShiftsLazyRouteImport = createFileRoute(
  '/_authLayout/_adminLayout/shifts',
)()
const AuthLayoutAdminLayoutSettingLazyRouteImport = createFileRoute(
  '/_authLayout/_adminLayout/setting',
)()
const AuthLayoutAdminLayoutOverviewLazyRouteImport = createFileRoute(
  '/_authLayout/_adminLayout/overview',
)()
const AuthLayoutAdminLayoutUsersUserIdLazyRouteImport = createFileRoute(
  '/_authLayout/_adminLayout/users/$userId',
)()

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutMyShiftsLazyRoute = AuthLayoutMyShiftsLazyRouteImport.update({
  id: '/myShifts',
  path: '/myShifts',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_authLayout/myShifts.lazy').then((d) => d.Route),
)
const AuthLayoutMyScheduleLazyRoute =
  AuthLayoutMyScheduleLazyRouteImport.update({
    id: '/mySchedule',
    path: '/mySchedule',
    getParentRoute: () => AuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authLayout/mySchedule.lazy').then((d) => d.Route),
  )
const AuthLayoutVacantShiftsRoute = AuthLayoutVacantShiftsRouteImport.update({
  id: '/vacantShifts',
  path: '/vacantShifts',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminLayoutRoute = AuthLayoutAdminLayoutRouteImport.update({
  id: '/_adminLayout',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminLayoutUsersLazyRoute =
  AuthLayoutAdminLayoutUsersLazyRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthLayoutAdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authLayout/_adminLayout/users.lazy').then((d) => d.Route),
  )
const AuthLayoutAdminLayoutSitesLazyRoute =
  AuthLayoutAdminLayoutSitesLazyRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => AuthLayoutAdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authLayout/_adminLayout/sites.lazy').then((d) => d.Route),
  )
const AuthLayoutAdminLayoutShiftsLazyRoute =
  AuthLayoutAdminLayoutShiftsLazyRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => AuthLayoutAdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authLayout/_adminLayout/shifts.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutAdminLayoutSettingLazyRoute =
  AuthLayoutAdminLayoutSettingLazyRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => AuthLayoutAdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authLayout/_adminLayout/setting.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutAdminLayoutOverviewLazyRoute =
  AuthLayoutAdminLayoutOverviewLazyRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthLayoutAdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authLayout/_adminLayout/overview.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutAdminLayoutUsersUserIdLazyRoute =
  AuthLayoutAdminLayoutUsersUserIdLazyRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthLayoutAdminLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authLayout/_adminLayout/users.$userId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vacantShifts': typeof AuthLayoutVacantShiftsRoute
  '/mySchedule': typeof AuthLayoutMyScheduleLazyRoute
  '/myShifts': typeof AuthLayoutMyShiftsLazyRoute
  '/overview': typeof AuthLayoutAdminLayoutOverviewLazyRoute
  '/setting': typeof AuthLayoutAdminLayoutSettingLazyRoute
  '/shifts': typeof AuthLayoutAdminLayoutShiftsLazyRoute
  '/sites': typeof AuthLayoutAdminLayoutSitesLazyRoute
  '/users': typeof AuthLayoutAdminLayoutUsersLazyRoute
  '/users/$userId': typeof AuthLayoutAdminLayoutUsersUserIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vacantShifts': typeof AuthLayoutVacantShiftsRoute
  '/mySchedule': typeof AuthLayoutMyScheduleLazyRoute
  '/myShifts': typeof AuthLayoutMyShiftsLazyRoute
  '/overview': typeof AuthLayoutAdminLayoutOverviewLazyRoute
  '/setting': typeof AuthLayoutAdminLayoutSettingLazyRoute
  '/shifts': typeof AuthLayoutAdminLayoutShiftsLazyRoute
  '/sites': typeof AuthLayoutAdminLayoutSitesLazyRoute
  '/users': typeof AuthLayoutAdminLayoutUsersLazyRoute
  '/users/$userId': typeof AuthLayoutAdminLayoutUsersUserIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_authLayout/_adminLayout': typeof AuthLayoutAdminLayoutRouteWithChildren
  '/_authLayout/vacantShifts': typeof AuthLayoutVacantShiftsRoute
  '/_authLayout/mySchedule': typeof AuthLayoutMyScheduleLazyRoute
  '/_authLayout/myShifts': typeof AuthLayoutMyShiftsLazyRoute
  '/_authLayout/_adminLayout/overview': typeof AuthLayoutAdminLayoutOverviewLazyRoute
  '/_authLayout/_adminLayout/setting': typeof AuthLayoutAdminLayoutSettingLazyRoute
  '/_authLayout/_adminLayout/shifts': typeof AuthLayoutAdminLayoutShiftsLazyRoute
  '/_authLayout/_adminLayout/sites': typeof AuthLayoutAdminLayoutSitesLazyRoute
  '/_authLayout/_adminLayout/users': typeof AuthLayoutAdminLayoutUsersLazyRoute
  '/_authLayout/_adminLayout/users/$userId': typeof AuthLayoutAdminLayoutUsersUserIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vacantShifts'
    | '/mySchedule'
    | '/myShifts'
    | '/overview'
    | '/setting'
    | '/shifts'
    | '/sites'
    | '/users'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vacantShifts'
    | '/mySchedule'
    | '/myShifts'
    | '/overview'
    | '/setting'
    | '/shifts'
    | '/sites'
    | '/users'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_authLayout/_adminLayout'
    | '/_authLayout/vacantShifts'
    | '/_authLayout/mySchedule'
    | '/_authLayout/myShifts'
    | '/_authLayout/_adminLayout/overview'
    | '/_authLayout/_adminLayout/setting'
    | '/_authLayout/_adminLayout/shifts'
    | '/_authLayout/_adminLayout/sites'
    | '/_authLayout/_adminLayout/users'
    | '/_authLayout/_adminLayout/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/myShifts': {
      id: '/_authLayout/myShifts'
      path: '/myShifts'
      fullPath: '/myShifts'
      preLoaderRoute: typeof AuthLayoutMyShiftsLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/mySchedule': {
      id: '/_authLayout/mySchedule'
      path: '/mySchedule'
      fullPath: '/mySchedule'
      preLoaderRoute: typeof AuthLayoutMyScheduleLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/vacantShifts': {
      id: '/_authLayout/vacantShifts'
      path: '/vacantShifts'
      fullPath: '/vacantShifts'
      preLoaderRoute: typeof AuthLayoutVacantShiftsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/_adminLayout': {
      id: '/_authLayout/_adminLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutAdminLayoutRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/_adminLayout/users': {
      id: '/_authLayout/_adminLayout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthLayoutAdminLayoutUsersLazyRouteImport
      parentRoute: typeof AuthLayoutAdminLayoutRoute
    }
    '/_authLayout/_adminLayout/sites': {
      id: '/_authLayout/_adminLayout/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthLayoutAdminLayoutSitesLazyRouteImport
      parentRoute: typeof AuthLayoutAdminLayoutRoute
    }
    '/_authLayout/_adminLayout/shifts': {
      id: '/_authLayout/_adminLayout/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthLayoutAdminLayoutShiftsLazyRouteImport
      parentRoute: typeof AuthLayoutAdminLayoutRoute
    }
    '/_authLayout/_adminLayout/setting': {
      id: '/_authLayout/_adminLayout/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AuthLayoutAdminLayoutSettingLazyRouteImport
      parentRoute: typeof AuthLayoutAdminLayoutRoute
    }
    '/_authLayout/_adminLayout/overview': {
      id: '/_authLayout/_adminLayout/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthLayoutAdminLayoutOverviewLazyRouteImport
      parentRoute: typeof AuthLayoutAdminLayoutRoute
    }
    '/_authLayout/_adminLayout/users/$userId': {
      id: '/_authLayout/_adminLayout/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthLayoutAdminLayoutUsersUserIdLazyRouteImport
      parentRoute: typeof AuthLayoutAdminLayoutRoute
    }
  }
}

interface AuthLayoutAdminLayoutRouteChildren {
  AuthLayoutAdminLayoutOverviewLazyRoute: typeof AuthLayoutAdminLayoutOverviewLazyRoute
  AuthLayoutAdminLayoutSettingLazyRoute: typeof AuthLayoutAdminLayoutSettingLazyRoute
  AuthLayoutAdminLayoutShiftsLazyRoute: typeof AuthLayoutAdminLayoutShiftsLazyRoute
  AuthLayoutAdminLayoutSitesLazyRoute: typeof AuthLayoutAdminLayoutSitesLazyRoute
  AuthLayoutAdminLayoutUsersLazyRoute: typeof AuthLayoutAdminLayoutUsersLazyRoute
  AuthLayoutAdminLayoutUsersUserIdLazyRoute: typeof AuthLayoutAdminLayoutUsersUserIdLazyRoute
}

const AuthLayoutAdminLayoutRouteChildren: AuthLayoutAdminLayoutRouteChildren = {
  AuthLayoutAdminLayoutOverviewLazyRoute:
    AuthLayoutAdminLayoutOverviewLazyRoute,
  AuthLayoutAdminLayoutSettingLazyRoute: AuthLayoutAdminLayoutSettingLazyRoute,
  AuthLayoutAdminLayoutShiftsLazyRoute: AuthLayoutAdminLayoutShiftsLazyRoute,
  AuthLayoutAdminLayoutSitesLazyRoute: AuthLayoutAdminLayoutSitesLazyRoute,
  AuthLayoutAdminLayoutUsersLazyRoute: AuthLayoutAdminLayoutUsersLazyRoute,
  AuthLayoutAdminLayoutUsersUserIdLazyRoute:
    AuthLayoutAdminLayoutUsersUserIdLazyRoute,
}

const AuthLayoutAdminLayoutRouteWithChildren =
  AuthLayoutAdminLayoutRoute._addFileChildren(
    AuthLayoutAdminLayoutRouteChildren,
  )

interface AuthLayoutRouteChildren {
  AuthLayoutAdminLayoutRoute: typeof AuthLayoutAdminLayoutRouteWithChildren
  AuthLayoutVacantShiftsRoute: typeof AuthLayoutVacantShiftsRoute
  AuthLayoutMyScheduleLazyRoute: typeof AuthLayoutMyScheduleLazyRoute
  AuthLayoutMyShiftsLazyRoute: typeof AuthLayoutMyShiftsLazyRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAdminLayoutRoute: AuthLayoutAdminLayoutRouteWithChildren,
  AuthLayoutVacantShiftsRoute: AuthLayoutVacantShiftsRoute,
  AuthLayoutMyScheduleLazyRoute: AuthLayoutMyScheduleLazyRoute,
  AuthLayoutMyShiftsLazyRoute: AuthLayoutMyShiftsLazyRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
